feat: готов проект спринт 15!
DenniKs/java-shareit pull request #2
Opened 2024-10-27 18:52 UTC by DenniKs

Добрый вечер!

2024-10-28 13:38 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-10-28 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        } else {
1. `else` не нужен в таком случае. Достаточно написать `return null;` ниже условного оператора
2. Возможно в случае, когда нам на вход приходит `null` лучше выбрасывать исключение

2024-10-28 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        } else {
Аналогично тому, что писал выше

2024-10-28 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    private final ItemServiceImpl itemService;
С точки зрения слоеной архитектуры, маппер -- это внешная структура, он не должен знать о существовании никаких сервисов, чтобы этого добиться ему нужно передавать на вход метода все необхоимые структуры, а там где мы его вызываем делать вызов сервисов или хранилищ

2024-10-28 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    private final ItemMapper itemMapper;
Маппер, обычно, это легковесная структура, которая не знает о других мапперах, чтобы этого добиться, на вход методу можно подавать уже смаппленные объекты, но это необязательно (в отличие, от сервисов, мапперы можно оставить и здесь)

2024-10-28 13:38 UTC, LexLippi commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users, items, bookings, item_request, comments;
Этой строчки не должно быть в миграции. 
Представь себе приложение, в котором при каждом обновлении удаляются пользовательские данные. Никто не захочет пользоваться таким)

2024-10-28 13:38 UTC, LexLippi commented on src/main/resources/schema.sql
> +    available BOOLEAN,
Кажется, не хватает ограничения `not null`

2024-10-28 13:38 UTC, LexLippi commented on src/main/resources/schema.sql
> +    status VARCHAR (25),
кажется, что не хватает ограничения `not null`, потому что у бронирования всегда есть какой-то статус

2024-10-28 13:38 UTC, LexLippi commented on src/main/resources/schema.sql
> +    text      VARCHAR(1024)                           NOT NULL,
Лучше не называть поля таблицы аналогично типу данных зарезервированному в стандарте, либо использовать экранирование с помощью \`\`

2024-10-28 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            if (repository.findByEmail(userDto.getEmail())
Можно инвертировать условной оператор и избавиться от ветки `else`, это снизит [цикломатическую сложность кода](https://en.wikipedia.org/wiki/Cyclomatic_complexity#:~:text=Cyclomatic%20complexity%20is%20a%20software,McCabe%2C%20Sr.)

2024-10-28 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +@Component
Зачем менять аннотацию, если внутренняя структура не изменилась, а методы можно сделать статическими и обращться к ним без создания объекта-маппера?

Такой подход позволит существенно уменьшить количество внедряемых зависимостей, а значит в будущем позволит ускорить сборку проекта

2024-10-28 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (booking != null) {
Можно инвертировать оператор и избавиться от `else`

2024-10-28 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        } else return new ArrayList<>();
`else` не нужен

2024-10-28 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        }
Можно использовать тернарный оператор и тогда нам не придется объявлять переменную до инициализации, что является не лучшим подходом

2024-10-28 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/service/CheckConsistencyService.java
> +    }
Не очень понятно, какое отношение эти методы имеют к проверки консистентности. Кажется, что никакой, а значит их тут быть не должно

2024-10-28 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        } else {
`else` не нужен

2024-10-28 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            }
можно использовать тернарный оператор внутри вызова конструктора `ValidationException`

2024-10-28 13:38 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            if (!approved) {
можно инвертировать оператор и избавиться от `else`

2024-10-29 16:46 UTC, DenniKs commented
Привет!

Внесены правки по итога ревью.

2024-10-30 16:27 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Осталось одно замечание, которое необходимо исправить!

Желаю удачи!

2024-10-30 16:27 UTC, LexLippi commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users, items, bookings, item_request, comments;
Эту строчку надо удалить, как уже писал :)

2024-10-30 17:17 UTC, DenniKs commented
Привет!

Я ее удалял, а потом вернул, когда ошибки правил и закомитил значит)

2024-10-31 17:51 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-10-31 18:25 UTC, merged