Add item requests and gateway
DenniKs/java-shareit pull request #3
Opened 2024-11-06 23:13 UTC by DenniKs

2024-11-07 00:48 UTC, DenniKs commented
Привет!

Отправляю на проверку сделанный проект спринта 16!

Уезжаю на неделю, времени на исправление останется мало до жесткого дедлайна, так что не суди сильно строго, пожалуйста :) Хотя любые замечания придется исправлять в любом случае.

Заранее спасибо!

2024-11-07 16:32 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-11-07 16:32 UTC, LexLippi commented on server/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users, items, bookings, item_request, comments;
Вот этого в реальной миграции быть не должно.

Никто не захочет пользоваться приложением, в котором при каждом обновлении удаляются данные пользователей

2024-11-07 16:32 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                     @PositiveOrZero @RequestParam(name = "from", defaultValue = "0")
в `name` нет необходимости, если оно совпадает с названием переменной

2024-11-07 16:32 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingState.java
> +        return Optional.empty();
Это лучше переписать с использованием Stream API

2024-11-07 16:58 UTC, DenniKs commented on server/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users, items, bookings, item_request, comments;
Снова забыл удалить после теста, спасибо!

2024-11-08 18:29 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи с дипломным проектом!

2024-11-10 20:53 UTC, merged